# Generated by Django 3.2.5 on 2021-08-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
