# Generated by Django 3.2.5 on 2021-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0002_show_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
