# Generated by Django 3.2.5 on 2021-08-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://icon-library.com/images/coder-icon/coder-icon-26.jpg'),
        ),
    ]
