# Generated by Django 3.2.5 on 2021-08-31 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='comment',
            new_name='message',
        ),
    ]
